In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score,mean_squared_error,mean_absolute_error
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor

In [2]:
data = pd.read_csv('/Users/Ethan/Downloads/homelessdata.csv',encoding='latin1', low_memory=False)

In [3]:
data

,Agencies Agency Name,Clients Age Tier,Clients Ethnicity,Clients Race,Clients Veteran Status,Clients Unique Identifier,Enrollments Days from Project Start to Move-In,Enrollments Days in Project,Enrollments Project Start Date,Enrollments Project Exit Date,...,Entry Screen SSDI (Yes / No),Entry Screen SSI (Yes / No),Entry Screen TANF (Yes / No),Entry Screen Non-Cash Benefit from Any Source,Enrollments Count Children,Enrollments Household Type,Enrollments Individual or Family,Enrollments Average Days from Project Start to Move-In,Enrollments Average Days in Project,Enrollments Count Chronic Homeless Households
0,AbS - Abode Services,45 to 54,Hispanic/Latino,White,No,75B1DC866,NaN,299,6/29/2018,NaN,...,No,No,No,Yes,0,Household without Children,Individual,NaN,299,0
1,AbS - Abode Services,45 to 54,Non-Hispanic/Non-Latino,Black or African American,No,179156ACC,NaN,231,6/29/2018,2/15/2019,...,No,No,No,No,0,Household without Children,Individual,NaN,231,0
2,AbS - Abode Services,45 to 54,Non-Hispanic/Non-Latino,White,No,F89729E91,NaN,139,6/29/2018,11/15/2018,...,No,No,No,Yes,0,Household without Children,Individual,NaN,139,1
3,BACS - Bay Area Community Services,25 to 34,Non-Hispanic/Non-Latino,White,No,C1A7A95B1,NaN,103,6/29/2018,10/10/2018,...,No,No,No,Yes,0,Household without Children,Individual,NaN,103,1
4,BACS - Bay Area Community Services,35 to 44,Hispanic/Latino,White,No,B47E8D743,NaN,103,6/29/2018,10/10/2018,...,No,Yes,No,No,0,Household without Children,Individual,NaN,103,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77796,BOSS - Building Opportunities for Self Suffici...,65 or Above,Non-Hispanic/Non-Latino,White,No,4C5173628,-2,7030,8/7/1994,11/5/2013,...,No,Yes,No,No,0,Household without Children,Individual,-2.0,7030,0
77797,BOSS - Building Opportunities for Self Suffici...,65 or Above,Non-Hispanic/Non-Latino,White,No,4C5173628,-2,9026,8/7/1994,NaN,...,No,Yes,No,No,0,Household without Children,Individual,-2.0,9026,0
77798,ACHCD - Housing and Community Development,25 to 34,Non-Hispanic/Non-Latino,Black or African American,No,1C9B22C19,0,9483,5/7/1993,NaN,...,No,Yes,No,No,1,Household with Children,Family,0.0,9483,0
77799,ACHCD - Housing and Community Development,65 or Above,Non-Hispanic/Non-Latino,Black or African American,No,3A68BACDC,0,9483,5/7/1993,NaN,...,No,No,Yes,Yes,1,Household with Children,Family,0.0,9483,0
77800,ACHCD - Housing and Community Development,45 to 54,Hispanic/Latino,White,No,779D418BC,0,9493,4/27/1993,NaN,...,No,No,No,No,0,Household without Children,Individual,0.0,9493,0

In [4]:
data['Enrollments Project Start Date']

0        6/29/2018
1        6/29/2018
2        6/29/2018
3        6/29/2018
4        6/29/2018
           ...
77796     8/7/1994
77797     8/7/1994
77798     5/7/1993
77799     5/7/1993
77800    4/27/1993
Name: Enrollments Project Start Date, Length: 77801, dtype: object

In [5]:
#changed the dates from an object to datetime
data['Enrollments Project Start Date'] = pd.to_datetime(data['Enrollments Project Start Date'], errors = 'coerce')
data['Enrollments Project Start Date']

0       2018-06-29
1       2018-06-29
2       2018-06-29
3       2018-06-29
4       2018-06-29
           ...
77796   1994-08-07
77797   1994-08-07
77798   1993-05-07
77799   1993-05-07
77800   1993-04-27
Name: Enrollments Project Start Date, Length: 77801, dtype: datetime64[ns]

In [6]:
data.head(5)

,Agencies Agency Name,Clients Age Tier,Clients Ethnicity,Clients Race,Clients Veteran Status,Clients Unique Identifier,Enrollments Days from Project Start to Move-In,Enrollments Days in Project,Enrollments Project Start Date,Enrollments Project Exit Date,...,Entry Screen SSDI (Yes / No),Entry Screen SSI (Yes / No),Entry Screen TANF (Yes / No),Entry Screen Non-Cash Benefit from Any Source,Enrollments Count Children,Enrollments Household Type,Enrollments Individual or Family,Enrollments Average Days from Project Start to Move-In,Enrollments Average Days in Project,Enrollments Count Chronic Homeless Households
0,AbS - Abode Services,45 to 54,Hispanic/Latino,White,No,75B1DC866,NaN,299,2018-06-29,NaN,...,No,No,No,Yes,0,Household without Children,Individual,NaN,299,0
1,AbS - Abode Services,45 to 54,Non-Hispanic/Non-Latino,Black or African American,No,179156ACC,NaN,231,2018-06-29,2/15/2019,...,No,No,No,No,0,Household without Children,Individual,NaN,231,0
2,AbS - Abode Services,45 to 54,Non-Hispanic/Non-Latino,White,No,F89729E91,NaN,139,2018-06-29,11/15/2018,...,No,No,No,Yes,0,Household without Children,Individual,NaN,139,1
3,BACS - Bay Area Community Services,25 to 34,Non-Hispanic/Non-Latino,White,No,C1A7A95B1,NaN,103,2018-06-29,10/10/2018,...,No,No,No,Yes,0,Household without Children,Individual,NaN,103,1
4,BACS - Bay Area Community Services,35 to 44,Hispanic/Latino,White,No,B47E8D743,NaN,103,2018-06-29,10/10/2018,...,No,Yes,No,No,0,Household without Children,Individual,NaN,103,1

In [7]:
#dropped columns that were repetitive and not needed for conducting the prediction model
data.drop(columns = ['Clients Ethnicity','Clients American Indian or Alaska Native'
                    ,'Clients Asian','Clients Black or African American','Clients Native Hawaiian or Other Pacific Islander'
                    ,'Clients White','Entry Screen Education Degree','Entry Screen Employment Seeking',
                    'Update/Exit Custom Current Program Phase','Update/Exit Screen Housing Status'
                    ,'Enrollments Days from Project Start to Move-In',
                    'Enrollments Project Exit Date','Inbound Recidivism Days Since Last Exit',
                    'Outbound Recidivism Days Until Next Entry','Outbound Recidivism Next Entry Date',
                    'Program Inventory End Date','Program Inventory Start Date','Programs Added Date','Update/Exit Screen Exit Destination'
                    ,'Update/Exit Screen Housed on Exit','Clients Global Household - Head of Household (HoH)',
                    'Clients Discharge Status','Enrollments Last Exit Destination','Entry Screen Currently Fleeing Domestic Violence',
                    'Enrollments Average Days from Project Start to Move-In','Enrollments Average Days in Project',
                    'Entry Screen Non-Cash Benefit from Any Source','Entry Screen Income from any Source',
                    'Entry Screen Earned Income Tiers','Enrollments Count Children','Clients Unique Identifier'], inplace = True)

In [8]:
data.dropna(inplace = True)

In [9]:
data.describe()

,Enrollments Days in Project,Enrollments Count Chronic Homeless Households
count,73979.000000,73979.000000
mean,436.191041,0.186472
std,822.732069,0.389490
min,-190.000000,0.000000
25%,25.000000,0.000000
50%,135.000000,0.000000
75%,443.000000,0.000000
max,9493.000000,1.000000

In [10]:
#only wanted data that were within the 10 year period of recording
#any enrollments that started before 2008 were removed

data1 = data.loc[data['Enrollments Project Start Date'] >= '1/1/2008']
data1

,Agencies Agency Name,Clients Age Tier,Clients Race,Clients Veteran Status,Enrollments Days in Project,Enrollments Project Start Date,Entry Screen Residence Prior to Project Entry,Inbound Recidivism Appeared Before (Yes / No),Inbound Recidivism Appeared Before In Same Program (Yes / No),Inbound Recidivism Appeared Before with Stable Housing (Yes / No),...,Entry Screen General Assistance (Yes / No),Entry Screen Pension or retirement income from a former job (Yes / No),Entry Screen Private Disability Insurance (Yes / No),Entry Screen Social Security Retirement Income (Yes / No),Entry Screen SSDI (Yes / No),Entry Screen SSI (Yes / No),Entry Screen TANF (Yes / No),Enrollments Household Type,Enrollments Individual or Family,Enrollments Count Chronic Homeless Households
0,AbS - Abode Services,45 to 54,White,No,299,2018-06-29,"Rental by client, with other housing subsidy (...",Yes,No,Yes,...,Yes,No,No,No,No,No,No,Household without Children,Individual,0
1,AbS - Abode Services,45 to 54,Black or African American,No,231,2018-06-29,Permanent housing (other than RRH) for formerl...,Yes,No,No,...,No,No,No,No,No,No,No,Household without Children,Individual,0
2,AbS - Abode Services,45 to 54,White,No,139,2018-06-29,Place not meant for habitation,Yes,No,No,...,No,No,No,No,No,No,No,Household without Children,Individual,1
3,BACS - Bay Area Community Services,25 to 34,White,No,103,2018-06-29,"Emergency Shelter, including hotel/motel paid ...",Yes,No,Yes,...,Yes,No,No,No,No,No,No,Household without Children,Individual,1
4,BACS - Bay Area Community Services,35 to 44,White,No,103,2018-06-29,Place not meant for habitation,Yes,No,Yes,...,No,No,No,No,No,Yes,No,Household without Children,Individual,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76159,GI - Goodwill Industries of the Greater East Bay,55 to 64,Multi-racial,Yes,2093,2008-01-07,"Emergency Shelter, including hotel/motel paid ...",No,No,No,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Household without Children,Individual,0
76160,SMC - St. Mary's Center,65 or Above,American Indian or Alaska Native,No,1638,2008-01-05,Client refused,No,No,No,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Household without Children,Individual,0
76161,ACHCD - Housing and Community Development,65 or Above,Black or African American,No,4128,2008-01-04,Place not meant for habitation,No,No,No,...,Yes,No,No,No,No,No,No,Household without Children,Individual,0
76162,GI - Goodwill Industries of the Greater East Bay,35 to 44,Black or African American,No,2096,2008-01-04,"Emergency Shelter, including hotel/motel paid ...",No,No,No,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Household without Children,Individual,0
76163,BOSS - Building Opportunities for Self Suffici...,35 to 44,Black or African American,No,2204,2008-01-02,Place not meant for habitation,No,No,No,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Household without Children,Individual,0

In [11]:
#I only looked for enrollment days greater than 2 because if a client were to stay for less than 2 days
#it would not be helpful to predict short stays
data2 = data1.loc[data1['Enrollments Days in Project'] >= 2, :]
data2.describe()

,Enrollments Days in Project,Enrollments Count Chronic Homeless Households
count,63093.000000,63093.000000
mean,411.618690,0.160446
std,606.766047,0.367022
min,2.000000,0.000000
25%,53.000000,0.000000
50%,180.000000,0.000000
75%,477.000000,0.000000
max,4128.000000,1.000000

In [12]:
data3 = pd.get_dummies(data2, drop_first = True)
#changing categorical columns into dummies

In [13]:
data3.head(10)

,Enrollments Days in Project,Enrollments Project Start Date,Enrollments Count Chronic Homeless Households,Agencies Agency Name_ACHCD - Housing and Community Development,Agencies Agency Name_APC - Alameda Point Collaborative,Agencies Agency Name_AbS - Abode Services,Agencies Agency Name_BACS - Bay Area Community Services,Agencies Agency Name_BFHP - Berkeley Food and Housing Project,Agencies Agency Name_BFWC - Building Futures with Women and Children,Agencies Agency Name_BH - Bonita House,...,Entry Screen Pension or retirement income from a former job (Yes / No)_Yes,Entry Screen Private Disability Insurance (Yes / No)_Yes,Entry Screen Social Security Retirement Income (Yes / No)_Yes,Entry Screen SSDI (Yes / No)_Yes,Entry Screen SSI (Yes / No)_Yes,Entry Screen TANF (Yes / No)_Yes,Enrollments Household Type_Household without Children,Enrollments Household Type_Households with only Children,Enrollments Household Type_Unknown,Enrollments Individual or Family_Individual
0,299,2018-06-29,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,231,2018-06-29,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,139,2018-06-29,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,103,2018-06-29,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,103,2018-06-29,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,1
5,290,2018-06-29,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,1
6,199,2018-06-29,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,1
10,3,2018-06-29,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
13,83,2018-06-29,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
15,10,2018-06-29,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [14]:
#dropping this column because it is not needed in the prediction model
data3.drop(columns = ['Enrollments Project Start Date'], inplace = True)

In [15]:
#dropping this column because this will have an impact on the predicted number of days
x = data3.drop('Enrollments Days in Project', axis = 1)

In [16]:
#creating the x test, x train, y test, y train, doing a 20-80 split
labels = data3['Enrollments Days in Project']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,labels, test_size = 0.2)

In [17]:
np.mean(y_train)

412.12715457463247

In [18]:
#linear regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
pred_lr = lr.predict(x_test)
score_lr = lr.score(x_train,y_train)
print(score_lr)
print(lr.coef_[0])
print(lr.intercept_)
preco_lr = data2['Enrollments Days in Project']
predict_lr = pd.Series(pred_lr)
mae_lr = mean_absolute_error(y_test,pred_lr)
mse_lr = mean_squared_error(y_test,pred_lr)
rmse_lr = np.sqrt(mse_lr)

print('Mae_lr: ',mae_lr)
print('Mse_lr: ',mse_lr)
print('Rmse_lr: ',rmse_lr)

0.627933950488069
-38.176198180199314
12768452544059.45
Mae_lr:  1135081160.4221184
Mse_lr:  6.357331031023397e+21
Rmse_lr:  79732872963.56125

In [19]:
#decision tree regressor
dtr = DecisionTreeRegressor(random_state=0)
dtr.fit(x_train,y_train)
pred_dtr = dtr.predict(x_test)
score_dtr = dtr.score(x_train,y_train)
print(score_dtr)
mae_dtr = mean_absolute_error(y_test,pred_dtr)
mse_dtr = mean_squared_error(y_test,pred_dtr)
rmse_dtr = np.sqrt(mse_dtr)
print('Mae_dtr: ',mae_dtr)
print('Mse_dtr: ',mse_dtr)
print('Rmse_dtr: ',rmse_dtr)

0.9567641649587867
Mae_dtr:  209.52576756497814
Mse_dtr:  167184.3348608881
Rmse_dtr:  408.881810381543

In [20]:
#random forest
rfr = RandomForestRegressor(n_estimators=200)
rfr.fit(x_train,y_train)
score_rfr = rfr.score(x_train,y_train)
print(score_rfr)
pred_rfr = rfr.predict(x_test)
mae_rfr = mean_absolute_error(y_test,pred_rfr)
mse_rfr = mean_squared_error(y_test,pred_rfr)
rmse_rfr = np.sqrt(mean_squared_error(y_test,pred_rfr))
print('Mae: ',mae_rfr)
print('Mse: ',mse_rfr)
print('Rmse: ',rmse_rfr)

0.9277938674263692
Mae:  180.0829913278924
Mse:  104459.63479245809
Rmse:  323.2021577781592

In [21]:
#knn regressor
knr = KNeighborsRegressor(n_neighbors = 10)
knr.fit(x_train,y_train)
score_knr = knr.score(x_train,y_train)
print(score_knr)
pred_knr = knr.predict(x_test)
mae_knr = mean_absolute_error(y_test,pred_knr)
mse_knr = mean_squared_error(y_test,pred_knr)
rmse_knr = np.sqrt(mse_knr)
print('Mae_knr: ',mae_knr)
print('Mse_knr: ',mse_knr)
print('Rmse_knr: ',rmse_knr)

0.7267208509288027
Mae_knr:  205.419938188446
Mse_knr:  127787.77625485379
Rmse_knr:  357.47416166046713

In [27]:
#prediction of 411
def mape(actual,pred):
    return np.mean(np.abs((actual - pred) / actual)) * 100
actual = y_test
pred_set = [411]*12619
#Calculate the MAPE
result = mape(actual,pred_set)
#print the result
print("The mean absolute percentage error: ",result)
mae_knr = mean_absolute_error(y_test,pred_set)
mse_knr = mean_squared_error(y_test,pred_set)
rmse_knr = np.sqrt(mse_knr)
print('Mae_knr: ',mae_knr)
print('Mse_knr: ',mse_knr)
print('Rmse_knr: ',rmse_knr)

The mean absolute percentage error:  1025.4941374092482
Mae_knr:  393.1494571677629
Mse_knr:  357222.326888026
Rmse_knr:  597.6807901279963

In [24]:
#get_dummies(data, drop_first = True)
#glm